version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "dependencies"
    # ignore:
    # - dependency-name: "typescript"
    # - dependency-name: "eslint"
